version: "3"

services:
  strugal:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./strugal:/strugal
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"