version: "3"

services:
  strugal:
    build:
      context: .
    ports:
      - "8002:8000"
    volumes:
      - ./:/strugal
    container_name: DAILYGESTION_APP
    command: >
      sh -c " cd strugal &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=vinhle
      - DB_PASS=password
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: DAILYGESTION_DB
    environment:
      - POSTGRES_DB=dailygestion
      - POSTGRES_USER=vinhle
      - POSTGRES_PASSWORD=Avengers2021
    ports:
      - "5434:5432"
