# Generated by Django 3.2.3 on 2021-08-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeRapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.CharField(max_length=255)),
                ('date_created', models.CharField(default='2021-08-01', max_length=255)),
                ('realise', models.BooleanField(default=False)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport.objectif')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierALR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=255, null=True)),
                ('prod_physique_p_r', models.FloatField(default=0)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('n_of', models.CharField(max_length=255)),
                ('date_created', models.CharField(default='2021-08-01', max_length=255)),
                ('realise', models.BooleanField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport.objectif')),
                ('typeR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport.typerapport')),
            ],
        ),
    ]
