# Generated by Django 3.1.7 on 2021-04-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planing', '0007_auto_20210407_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.FloatField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplan')),
            ],
        ),
    ]
