# Generated by Django 3.2 on 2021-05-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalierRPT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.FloatField()),
                ('date_created', models.CharField(default='2021-05-27', max_length=255)),
                ('realise', models.BooleanField(default=False)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplanrpt')),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierLC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.FloatField()),
                ('date_created', models.CharField(default='2021-05-27', max_length=255)),
                ('realise', models.BooleanField(default=False)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplanlc')),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierLB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.FloatField()),
                ('date_created', models.CharField(default='2021-05-27', max_length=255)),
                ('realise', models.BooleanField(default=False)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplanlb')),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.FloatField()),
                ('date_created', models.CharField(default='2021-05-27', max_length=255)),
                ('realise', models.BooleanField(default=False)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplane')),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('deche_geometrique', models.FloatField()),
                ('nbr_barre', models.FloatField()),
                ('n_of', models.FloatField()),
                ('date_created', models.CharField(default='2021-05-27', max_length=255)),
                ('realise', models.BooleanField(default=False)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplana')),
            ],
        ),
    ]
