# Generated by Django 3.2.3 on 2021-08-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournalieralr',
            name='date_created',
            field=models.CharField(default='2021-08-02', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-08-02', max_length=255),
        ),
    ]
