# Generated by Django 3.2 on 2021-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportjournaliera',
            name='deche_geometrique',
        ),
        migrations.RemoveField(
            model_name='rapportjournaliera',
            name='nbr_barre',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlb',
            name='deche_geometrique',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlb',
            name='nbr_barre',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlc',
            name='deche_geometrique',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlc',
            name='nbr_barre',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierrpt',
            name='deche_geometrique',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierrpt',
            name='nbr_barre',
        ),
        migrations.AddField(
            model_name='rapportjournaliera',
            name='obj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournaliera',
            name='prod_physique_p_r',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournaliere',
            name='obj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournalierlb',
            name='obj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournalierlb',
            name='prod_physique_p_r',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournalierlc',
            name='obj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournalierlc',
            name='prod_physique_p_r',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournalierrpt',
            name='obj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rapportjournalierrpt',
            name='prod_physique_p_r',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rapportjournaliera',
            name='date_created',
            field=models.CharField(default='2021-05-28', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-05-28', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlb',
            name='date_created',
            field=models.CharField(default='2021-05-28', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlc',
            name='date_created',
            field=models.CharField(default='2021-05-28', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierrpt',
            name='date_created',
            field=models.CharField(default='2021-05-28', max_length=255),
        ),
    ]
