# Generated by Django 3.2.3 on 2021-07-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournaliera',
            name='date_created',
            field=models.CharField(default='2021-07-29', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliera',
            name='realise',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-07-29', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlb',
            name='date_created',
            field=models.CharField(default='2021-07-29', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlc',
            name='date_created',
            field=models.CharField(default='2021-07-29', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierrpt',
            name='date_created',
            field=models.CharField(default='2021-07-29', max_length=255),
        ),
    ]
