# Generated by Django 3.1.7 on 2021-04-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportjournalier',
            options={'ordering': ['prod_physique']},
        ),
    ]
