# Generated by Django 3.1.7 on 2021-04-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0002_auto_20210411_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapportjournalier',
            options={},
        ),
    ]
