# Generated by Django 3.2.3 on 2021-07-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0002_alter_productionplan_typep'),
        ('rapport', '0002_auto_20210729_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RapportJournalierALR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_physique_p_r', models.FloatField(default=0)),
                ('prod_physique', models.FloatField()),
                ('prod_conforme', models.FloatField()),
                ('prod_non_conforme', models.FloatField()),
                ('n_of', models.CharField(max_length=255)),
                ('typeR', models.CharField(max_length=255)),
                ('date_created', models.CharField(default='2021-07-29', max_length=255)),
                ('realise', models.BooleanField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport.objectif')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.productionplan')),
            ],
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlb',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlc',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierrpt',
            name='ref',
        ),
        migrations.DeleteModel(
            name='RapportJournalierA',
        ),
        migrations.DeleteModel(
            name='RapportJournalierLB',
        ),
        migrations.DeleteModel(
            name='RapportJournalierLC',
        ),
        migrations.DeleteModel(
            name='RapportJournalierRPT',
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport.objectif'),
        ),
    ]
