# Generated by Django 3.2 on 2021-05-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0002_rapportjournaliera_rapportjournalierlb_rapportjournalierlc_rapportjournalierrpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournaliera',
            name='typeR',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='rapportjournaliere',
            name='typeR',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='rapportjournalierlb',
            name='typeR',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='rapportjournalierlc',
            name='typeR',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='rapportjournalierrpt',
            name='typeR',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
