# Generated by Django 3.2.3 on 2021-07-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0003_auto_20210729_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='rapportjournalieralr',
            name='typeR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport.typerapport'),
        ),
    ]
