# Generated by Django 3.1.7 on 2021-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0003_auto_20210411_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournalier',
            name='realise',
            field=models.BooleanField(default=False),
        ),
    ]
