# Generated by Django 3.2 on 2021-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0003_auto_20210520_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportjournaliera',
            name='typeR',
        ),
        migrations.RemoveField(
            model_name='rapportjournaliere',
            name='typeR',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlb',
            name='typeR',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierlc',
            name='typeR',
        ),
        migrations.RemoveField(
            model_name='rapportjournalierrpt',
            name='typeR',
        ),
    ]
