# Generated by Django 3.2.3 on 2021-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0004_auto_20210729_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typerapport',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
