# Generated by Django 3.2 on 2021-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0004_auto_20210520_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournaliera',
            name='date_created',
            field=models.CharField(default='2021-05-26', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-05-26', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlb',
            name='date_created',
            field=models.CharField(default='2021-05-26', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlc',
            name='date_created',
            field=models.CharField(default='2021-05-26', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierrpt',
            name='date_created',
            field=models.CharField(default='2021-05-26', max_length=255),
        ),
    ]
