# Generated by Django 3.1.7 on 2021-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0004_rapportjournalier_realise'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournalier',
            name='date_created',
            field=models.CharField(default='2021-04-17', max_length=255),
        ),
    ]
