# Generated by Django 3.2 on 2021-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0005_auto_20210531_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournaliera',
            name='date_created',
            field=models.CharField(default='2021-06-01', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-06-01', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlb',
            name='date_created',
            field=models.CharField(default='2021-06-01', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierlc',
            name='date_created',
            field=models.CharField(default='2021-06-01', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournalierrpt',
            name='date_created',
            field=models.CharField(default='2021-06-01', max_length=255),
        ),
    ]
