# Generated by Django 3.2.3 on 2021-07-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0002_alter_productionplan_typep'),
        ('rapport', '0005_alter_typerapport_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournalieralr',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.productionplan'),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.productionplan'),
        ),
    ]
