# Generated by Django 3.2.3 on 2021-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0005_auto_20210804_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournalieralr',
            name='date_created',
            field=models.CharField(default='2021-08-07', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-08-07', max_length=255),
        ),
    ]
