# Generated by Django 3.2.3 on 2021-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0006_auto_20210807_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournalieralr',
            name='date_created',
            field=models.CharField(default='2021-08-09', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='date_created',
            field=models.CharField(default='2021-08-09', max_length=255),
        ),
    ]
