# Generated by Django 3.2.3 on 2021-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0007_alter_rapportjournalieralr_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournaliere',
            name='ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
