# Generated by Django 3.1.7 on 2021-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('qte', models.FloatField()),
                ('longueur', models.FloatField()),
                ('ral', models.FloatField()),
            ],
        ),
    ]
