# Generated by Django 3.2 on 2021-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('ral', models.CharField(blank=True, max_length=255)),
                ('qte', models.FloatField()),
                ('typeP', models.CharField(default='Anodisation', max_length=255)),
                ('date_created', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('qte', models.FloatField()),
                ('typeP', models.CharField(default='extrusion', max_length=255)),
                ('date_created', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanLB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('qte', models.FloatField()),
                ('typeP', models.CharField(default='Laquage blan', max_length=255)),
                ('date_created', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanLC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('qte', models.FloatField()),
                ('ral', models.CharField(default='0M', max_length=255)),
                ('typeP', models.CharField(default='laquage couleurs', max_length=255)),
                ('date_created', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanRPT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref01', models.CharField(blank=True, max_length=255)),
                ('ref02', models.CharField(blank=True, max_length=255)),
                ('ral01', models.CharField(blank=True, max_length=255)),
                ('ral02', models.CharField(blank=True, max_length=255)),
                ('qte', models.FloatField()),
                ('typeP', models.CharField(default='RTP', max_length=255)),
                ('date_created', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
