# Generated by Django 3.2.3 on 2021-08-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='planned',
            field=models.BooleanField(default=True),
        ),
    ]
