# Generated by Django 3.1.7 on 2021-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='ref',
            field=models.CharField(max_length=255),
        ),
    ]
