# Generated by Django 3.1.7 on 2021-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0002_auto_20210405_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='longueur',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='ral',
        ),
    ]
