# Generated by Django 3.2.3 on 2021-08-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0002_alter_productionplan_planned'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePlaning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeP', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='typeP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planing.typeplaning'),
        ),
    ]
